server:
  port: 8762
spring:
  cloud:
    config:
      server:
        svn:
          uri: https://192.168.100.188/svn/Project/LMS2.0/configfile/desigin/
          username: zhuss
          password: zss123!
        default-label:
  profiles:
    active: subversion
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: config-server
    prefer-ip-address: true