server:
  port: 8762
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zhusensen/config-repo.git
          skipSslValidation: true
          search-paths:
          username:
          password:
          default-label: main
#svn
#        svn:
#          uri: https://192.168.100.188/svn/Project/LMS2.0/configfile/desigin/
#          username: zhuss
#          password: zss123!
#        default-label:
#svn
#  profiles:
#    active: subversion
  application:
    name: config-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: config-server
    prefer-ip-address: true