server:
  port: 8764
spring:
  application:
    name: busi-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: busi-server
    prefer-ip-address: true
word: test word